### ISSUE TITLE
bug: throwTimeOutError

### ISSUE THREAD

**Issue by trixlerjs** [ben-page/node-test#13]
Look at this file: https://github.com/ben-page/node-test/blob/master/lib/hook.js#L33

There is no such function in `util.js`,  And obviously no test to catch this? Is this code used at all?

**Comment by trixlerjs** [comment]
What is thid this non-existent function? A Bluebird code?

**Comment by ben-page** [comment]
Yeah, this was old and accidentally left in the hook.
