### ISSUE TITLE
No support for NodeJS event 

### ISSUE THREAD

**Issue by trixlerjs** [ben-page/node-test#2]
Hey. All test runners have build in NodeJS event support. Any plans for adding it?
`js-reporters` are used by all major test runners - Jasmine, Mocha, Karma etc. and to be compatible here you would need events. 
I saw you was planning to improve your reporter?

**Comment by ben-page** [comment]
Seems like a good idea. I'll look into this.

**Comment by ben-page** [comment]
I've added this to my Todo list.
