### ISSUE TITLE
execution time for each test.

### ISSUE THREAD

**Issue by trixlerjs** [ben-page/node-test#6]
Should you add execution time for each test? E.g. Mocha display duration only over a threshold. E.g.  `Foo (20420 ms) `.

And also maybe extend this in case a test take too long time to finish, you could auto-cancel the test after amount of time and output - `... test failed after 333 ms`. Just to avoid CPU and memory issues.

And if you are adding a debug option later on, it would be easy to debug if there is a execution time for each test when trying to figure out which test take too long to finish.

Btw. Karma have a retry function for failing test. Not sure if that is an option here.

**Comment by ben-page** [comment]
Executive time implemented in the current dev release. 

Automatically retrying a test is an extremely bad idea. With nothing validating that the test failed for the expected reason, any intermittent bug could slip through unnoticed. If someone truly needs to try more than once, they should build that logic into the test itself.
